// Generated by ReScript, PLEASE EDIT WITH CARE


function make(param) {
  return {
          scene: /* Standby */0,
          streamTitle: ""
        };
}

function setScene(state, scene) {
  return {
          scene: scene,
          streamTitle: state.streamTitle
        };
}

function setStreamTitle(state, streamTitle) {
  return {
          scene: state.scene,
          streamTitle: streamTitle
        };
}

function toStandby(state) {
  return setScene(state, /* Standby */0);
}

function toBrb(state) {
  return setScene(state, /* Brb */1);
}

function toOverlay(state) {
  return setScene(state, /* Overlay */2);
}

function isStandby(state) {
  return state.scene === /* Standby */0;
}

function stringify(t) {
  return JSON.stringify(t);
}

export {
  make ,
  setScene ,
  setStreamTitle ,
  toStandby ,
  toBrb ,
  toOverlay ,
  isStandby ,
  stringify ,
  
}
/* No side effect */
